### ISSUE TITLE
gitinfo2 Fehler

### ISSUE THREAD

**Issue by Milchshakee** [schiffe-versenken/ausarbeitung#3]
Ich bekomme diesen Fehler:

! Package gitinfo2 Error: I can't find the file 'gitHeadLocal.gin'
(gitinfo2)                Please check the manual (gitinfo2.pdf) 
(gitinfo2)                if you need more details.

**Comment by ghost** [comment]
Welches Betriebssystem verwendest du und wie erzeugst du die pdf?

Alternativ kannst du die Versionsinfo deaktivierten, indem du in Zeile 
46 den Parameter "grumpy" deaktivierst.

Am 26.12.2018 um 19:10 schrieb Christopher Schnick:

**Comment by Milchshakee** [comment]
Windows 10 mit TeXworks

**Comment by Milchshakee** [comment]
Kann man das Problem auch irgendwie beheben?

**Comment by Milchshakee** [comment]
Versuch mal, das Repo bei dir neu zu clonen und ob es dann bei dir immernoch funktioniert

**Comment by Milchshakee** [comment]
Außerdem sollte der Skript doch als git hook aufgerufen werden und nicht, wenn man die Pdf erzeugt

**Comment by ghost** [comment]
Ich habe eine Beispielkonfiguration für TeXworks in der Readme 
hinzugefügt. Funktioniert es damit?

Am 29.12.2018 um 11:12 schrieb Christopher Schnick:

**Comment by Milchshakee** [comment]
Das Problem an dem Skriptaufruf ist, dass die Variable %ProgramFiles% nicht expanded wird. Das ist in Tex nicht so einfach zu machen, daher sollte man das als hook realisieren

**Comment by ghost** [comment]
Bei mir funktioniert der Aufruf unter Windows 10 1803 mit Git 2.20.1 
problemlos
Der Nachteil an dem Hook ist, dass dadurch nicht erkannt wird, ob es 
Änderungen gibt, die noch nicht commited wurden. Falls du den Hook 
verwenden willst, kopiere die gitinfo2.sh als post-commit , post-merge 
und post-checkout nach .git/hooks .

Am 29.12.2018 um 11:44 schrieb Christopher Schnick:
